name: Package Application with Pyinstaller
description: 'GitHub Action to package python code with PyInstaller for Windows'
branding:
  icon: 'box'
  color: 'blue'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: /

    - uses: actions/upload-artifact@v2
      with:
        name: air-system
        path: /packages
